name: Deploy docs

on: 
  push:
    branches:
      -main

jobs: 
  build-and-deploy
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actionssetup-node@v3
        with: 
          node-version: 16

      - name: npm ci

      - run: npm run build

      - name: Deploy storybook
        working0directory: ;/packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}